name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * 0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install prerequesites
        run: |
          sudo apt-get update
          sudo apt-get install tree -y
          sudo apt-get -qq autoremove --purge
          sudo apt-get install jpegoptim -y
          sudo -E time bash scripts/install-webp.sh > /dev/null 2>&1
          sudo -E time bash scripts/install-optipng.sh > /dev/null 2>&1
          sudo wget -qO /usr/local/bin/avif https://github.com/Kagami/go-avif/releases/download/v0.1.0/avif-linux-x64
          sudo chmod +x /usr/local/bin/avif
          sudo cp optimize.sh /usr/local/bin/img-optimize
          sudo chmod 755 /usr/local/bin/img-optimize
          
      - name: Optimize Images
        run:  |
          ls -alh images/
          /usr/local/bin/img-optimize --all -q
          ls -alh images/
          /usr/local/bin/img-optimize --jpg -q
          /usr/local/bin/img-optimize --png -q
          rm images/*.webp
          /usr/local/bin/img-optimize --webp
          tree -L 2 .
          rm images/*.webp
          /usr/local/bin/img-optimize --webp --quiet
